version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis:14-master
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
